"""Curiosity memory — questions generated by ANIMA's self-directed learning.

Stores questions that arise from conversations: knowledge gaps, consistency
checks between beliefs, and curiosity about the operator. Questions go through
the same approval flow as beliefs — nothing sticks without Jerry's approval.
"""

import json
import os
import sqlite3
import uuid
from datetime import datetime, timezone

logger = __import__("logging").getLogger("curiosity")

VALID_TYPES = {"knowledge_gap", "consistency_check", "operator_curiosity"}
VALID_PRIORITIES = {"low", "medium", "high"}
VALID_STATUSES = {"open", "answered", "dissolved", "dismissed"}
PRIORITY_ORDER = {"high": 0, "medium": 1, "low": 2}


class CuriosityMemory:
    def __init__(self, config):
        self.config = config
        self.db_conn = None

    def initialize(self):
        # Use ANIMA_DATA_DIR if set, otherwise fall back to repo-relative path
        _data_dir = os.environ.get("ANIMA_DATA_DIR")
        base_dir = os.path.join(os.path.dirname(__file__), "..")
        if _data_dir:
            sqlite_path = os.path.normpath(
                os.path.join(_data_dir, "sqlite", "persistence.db")
            )
        else:
            sqlite_path = os.path.normpath(
                os.path.join(base_dir, self.config["memory"]["sqlite_path"])
            )
        os.makedirs(os.path.dirname(sqlite_path), exist_ok=True)
        self.db_conn = sqlite3.connect(sqlite_path, check_same_thread=False)
        self.db_conn.row_factory = sqlite3.Row
        self.db_conn.execute("PRAGMA journal_mode=WAL")
        self._create_tables()
        return self

    def _create_tables(self):
        self.db_conn.executescript("""
            CREATE TABLE IF NOT EXISTS questions (
                id TEXT PRIMARY KEY,
                question TEXT NOT NULL,
                question_type TEXT NOT NULL,
                context TEXT,
                topic_tags TEXT,
                source_episode TEXT,
                priority TEXT DEFAULT 'medium',
                status TEXT DEFAULT 'open',
                answer TEXT,
                answered_by TEXT,
                created_at TEXT NOT NULL,
                resolved_at TEXT,
                sleep_cycles_seen INTEGER DEFAULT 0
            );

            CREATE INDEX IF NOT EXISTS idx_questions_status ON questions(status);
            CREATE INDEX IF NOT EXISTS idx_questions_priority ON questions(priority);
        """)
        self.db_conn.commit()
        # Migration: add sleep_cycles_seen if table predates this column
        try:
            self.db_conn.execute(
                "ALTER TABLE questions ADD COLUMN sleep_cycles_seen INTEGER DEFAULT 0"
            )
            self.db_conn.commit()
        except sqlite3.OperationalError:
            pass  # column already exists
        # Migration: add exploration_count for B6 repetition guard
        try:
            self.db_conn.execute(
                "ALTER TABLE questions ADD COLUMN exploration_count INTEGER DEFAULT 0"
            )
            self.db_conn.commit()
        except sqlite3.OperationalError:
            pass

    def add_question(self, question, question_type, context=None,
                     topic_tags=None, source_episode=None, priority="medium",
                     embedder=None):
        """Add a new question. Returns the question ID, or None if duplicate.

        Enforces a soft gap ceiling: if open questions >= max_open_gaps,
        the lowest-priority oldest gap is dissolved before inserting.
        """
        if question_type not in VALID_TYPES:
            question_type = "knowledge_gap"
        if priority not in VALID_PRIORITIES:
            priority = "medium"

        if embedder is not None:
            from memory.dedup import is_duplicate
            open_rows = self.db_conn.execute(
                "SELECT question FROM questions WHERE status = 'open'"
            ).fetchall()
            open_texts = [r[0] for r in open_rows]
            candidate_emb = embedder.embed(question)
            corpus_embs = [(embedder.embed(t), t) for t in open_texts if t]
            dup, matched = is_duplicate(candidate_emb, corpus_embs, threshold=0.85)
            if dup:
                logger.info(
                    f"Gap dedup: skipped '{question[:60]}' — "
                    f"duplicate of '{matched[:60]}'"
                )
                return None

        # Target-domain bias — upgrade priority when the gap matches an
        # operator-configured target domain (research focus). Overrides the
        # saturation guard below for target domains.
        target_domains = set()
        try:
            target_domains = set(
                self.config.get("research", {}).get("target_domains", [])
            )
        except Exception:
            pass

        new_domain = None
        if topic_tags:
            new_domain = topic_tags[0] if isinstance(topic_tags, list) else None

        is_target = bool(new_domain and new_domain in target_domains)
        if is_target and priority != "high":
            priority = "high"
            logger.info(
                f"Target-domain bias: '{new_domain}' is a research target, "
                f"priority upgraded to high"
            )

        # Domain saturation guard — downgrade priority if domain already >40%
        # of open gaps. Skipped for target domains (they're the goal).
        if new_domain and not is_target:
            try:
                rows = self.db_conn.execute(
                    "SELECT topic_tags FROM questions WHERE status = 'open'"
                ).fetchall()
                total_open = len(rows)
                if total_open > 0:
                    domain_count = 0
                    for r in rows:
                        try:
                            tags = json.loads(r["topic_tags"] or "[]")
                            if tags and tags[0] == new_domain:
                                domain_count += 1
                        except (json.JSONDecodeError, TypeError):
                            pass
                    if domain_count / total_open > 0.4:
                        priority = "low"
                        logger.info(
                            f"Domain saturation guard: '{new_domain}' at "
                            f"{domain_count}/{total_open} ({domain_count/total_open:.0%}), "
                            f"downgrading to low priority"
                        )
            except Exception:
                pass

        question_id = str(uuid.uuid4())
        now = datetime.now(timezone.utc).isoformat()

        # Soft gap ceiling — dissolve lowest-priority gap if at capacity
        # Eviction prefers: lowest priority → most saturated domain → oldest
        # Investigation gaps (from hypothesis routing) bypass the ceiling —
        # they're system-requested and must not compete with regular gaps.
        is_investigation = source_episode and source_episode.startswith("hypothesis_")
        max_open = self.config.get("curiosity", {}).get("max_open_gaps", 25)
        open_count = self.get_question_count(status="open")
        if open_count >= max_open and not is_investigation:
            # Count domain frequency for saturation-aware eviction
            domain_freq = {}
            try:
                all_open = self.db_conn.execute(
                    "SELECT topic_tags FROM questions WHERE status = 'open'"
                ).fetchall()
                for r in all_open:
                    try:
                        tags = json.loads(r["topic_tags"] or "[]")
                        d = tags[0] if tags else "unclassified"
                    except (json.JSONDecodeError, TypeError):
                        d = "unclassified"
                    domain_freq[d] = domain_freq.get(d, 0) + 1
            except Exception:
                pass

            # Find lowest-priority, most-saturated-domain, oldest open gap to evict
            # PROTECT investigation gaps from eviction
            evict = self.db_conn.execute(
                "SELECT id, question, topic_tags FROM questions WHERE status = 'open' "
                "AND (source_episode IS NULL OR source_episode NOT LIKE 'hypothesis_%') "
                "ORDER BY CASE priority "
                "WHEN 'low' THEN 0 WHEN 'medium' THEN 1 WHEN 'high' THEN 2 END, "
                "created_at ASC LIMIT 10"
            ).fetchone()
            # Among low-priority candidates, prefer the most saturated domain
            if domain_freq:
                candidates = self.db_conn.execute(
                    "SELECT id, question, topic_tags FROM questions WHERE status = 'open' "
                    "AND (source_episode IS NULL OR source_episode NOT LIKE 'hypothesis_%') "
                    "ORDER BY CASE priority "
                    "WHEN 'low' THEN 0 WHEN 'medium' THEN 1 WHEN 'high' THEN 2 END, "
                    "created_at ASC LIMIT 10"
                ).fetchall()
                if candidates:
                    best_evict = None
                    best_freq = -1
                    for c in candidates:
                        try:
                            tags = json.loads(c["topic_tags"] or "[]")
                            d = tags[0] if tags else "unclassified"
                        except (json.JSONDecodeError, TypeError):
                            d = "unclassified"
                        freq = domain_freq.get(d, 0)
                        if freq > best_freq:
                            best_freq = freq
                            best_evict = c
                    if best_evict:
                        evict = best_evict

            if evict:
                self.dissolve_question(evict["id"], reason="Evicted — gap ceiling reached")
                logger.info(f"Gap ceiling ({max_open}): evicted '{evict['question'][:50]}'")

        self.db_conn.execute(
            "INSERT INTO questions (id, question, question_type, context, "
            "topic_tags, source_episode, priority, status, created_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, 'open', ?)",
            (question_id, question, question_type, context,
             json.dumps(topic_tags or []), source_episode, priority, now),
        )
        self.db_conn.commit()
        logger.info(f"New question: '{question[:60]}' ({question_type}, {priority})")
        return question_id

    def resolve_question(self, question_id, answer, answered_by="jerry"):
        """Mark a question as answered. Returns True if found."""
        now = datetime.now(timezone.utc).isoformat()
        cursor = self.db_conn.execute(
            "UPDATE questions SET status = 'answered', answer = ?, "
            "answered_by = ?, resolved_at = ? WHERE id = ? AND status = 'open'",
            (answer, answered_by, now, question_id),
        )
        self.db_conn.commit()
        return cursor.rowcount > 0

    def increment_exploration_count(self, question_id, max_explorations=3):
        """Increment exploration count for a gap. If >= max, retire as exhausted.

        Returns True if the gap was exhausted (retired), False otherwise.
        """
        self.db_conn.execute(
            "UPDATE questions SET exploration_count = COALESCE(exploration_count, 0) + 1 "
            "WHERE id = ?", (question_id,)
        )
        row = self.db_conn.execute(
            "SELECT COALESCE(exploration_count, 0) as ec FROM questions WHERE id = ?",
            (question_id,)
        ).fetchone()
        if row and row["ec"] >= max_explorations:
            now = datetime.now(timezone.utc).isoformat()
            self.db_conn.execute(
                "UPDATE questions SET status = 'dissolved', "
                "answer = 'Exhausted — explored ' || COALESCE(exploration_count, 0) || ' times without new output', "
                "resolved_at = ? WHERE id = ? AND status = 'open'",
                (now, question_id),
            )
            self.db_conn.commit()
            logger.info(f"Gap exhausted after {row['ec']} explorations: {question_id[:8]}")
            return True
        self.db_conn.commit()
        return False

    def dissolve_question(self, question_id, reason=None):
        """Mark a question as dissolved (no longer relevant)."""
        now = datetime.now(timezone.utc).isoformat()
        answer = reason or "No longer relevant"
        self.db_conn.execute(
            "UPDATE questions SET status = 'dissolved', answer = ?, "
            "resolved_at = ? WHERE id = ? AND status = 'open'",
            (answer, now, question_id),
        )
        self.db_conn.commit()

    def dismiss_question(self, question_id):
        """Mark a question as dismissed (rejected by operator)."""
        now = datetime.now(timezone.utc).isoformat()
        self.db_conn.execute(
            "UPDATE questions SET status = 'dismissed', resolved_at = ? "
            "WHERE id = ? AND status = 'open'",
            (now, question_id),
        )
        self.db_conn.commit()

    def get_open_questions(self, priority=None, question_type=None, limit=20):
        """Get open questions sorted by priority then date."""
        query = "SELECT * FROM questions WHERE status = 'open'"
        params = []

        if priority:
            query += " AND priority = ?"
            params.append(priority)
        if question_type:
            query += " AND question_type = ?"
            params.append(question_type)

        query += " ORDER BY CASE priority "
        query += "WHEN 'high' THEN 0 WHEN 'medium' THEN 1 WHEN 'low' THEN 2 END, "
        query += "created_at ASC LIMIT ?"
        params.append(limit)

        rows = self.db_conn.execute(query, params).fetchall()
        return [self._row_to_dict(r) for r in rows]

    def get_questions_by_topics(self, topics, status="open", limit=3):
        """Get questions whose topic_tags overlap with given topics."""
        query = "SELECT * FROM questions WHERE status = ?"
        rows = self.db_conn.execute(query, (status,)).fetchall()

        topic_set = {t.lower() for t in topics} if topics else set()
        matched = []
        for row in rows:
            row_dict = self._row_to_dict(row)
            row_topics = {t.lower() for t in row_dict.get("topic_tags", [])}
            overlap = topic_set & row_topics
            if overlap:
                row_dict["_topic_overlap"] = len(overlap)
                matched.append(row_dict)

        matched.sort(
            key=lambda x: (-x["_topic_overlap"], PRIORITY_ORDER.get(x["priority"], 1))
        )
        return matched[:limit]

    def get_high_priority_opener(self):
        """Get the single oldest high-priority open question for session opener."""
        row = self.db_conn.execute(
            "SELECT * FROM questions WHERE status = 'open' AND priority = 'high' "
            "ORDER BY created_at ASC LIMIT 1"
        ).fetchone()
        return self._row_to_dict(row) if row else None

    def get_question_count(self, status=None):
        """Count questions, optionally filtered by status."""
        if status:
            row = self.db_conn.execute(
                "SELECT COUNT(*) FROM questions WHERE status = ?", (status,)
            ).fetchone()
        else:
            row = self.db_conn.execute(
                "SELECT COUNT(*) FROM questions"
            ).fetchone()
        return row[0]

    def get_all_questions(self, limit=50):
        """Get all questions regardless of status."""
        rows = self.db_conn.execute(
            "SELECT * FROM questions ORDER BY created_at DESC LIMIT ?",
            (limit,),
        ).fetchall()
        return [self._row_to_dict(r) for r in rows]

    def apply_sleep_decay(self, decay_cycles=5, dissolve_cycles=10):
        """Increment sleep_cycles_seen on all open gaps, decay and dissolve stale ones.

        Called once per sleep consolidation pass.
        - After decay_cycles: demote priority (high→medium→low)
        - After dissolve_cycles: auto-close with status 'dissolved'
        """
        now = datetime.now(timezone.utc).isoformat()

        # Increment cycle counter on all open gaps
        self.db_conn.execute(
            "UPDATE questions SET sleep_cycles_seen = COALESCE(sleep_cycles_seen, 0) + 1 "
            "WHERE status = 'open'"
        )

        # Dissolve gaps past dissolve threshold
        # Investigation gaps (hypothesis_*) are protected — they're system-requested
        # and must survive until the investigation loop resolves them.
        dissolved = self.db_conn.execute(
            "UPDATE questions SET status = 'dissolved', answer = 'Stale — auto-dissolved after "
            "' || sleep_cycles_seen || ' sleep cycles', resolved_at = ? "
            "WHERE status = 'open' AND sleep_cycles_seen >= ? "
            "AND (source_episode IS NULL OR source_episode NOT LIKE 'hypothesis_%')",
            (now, dissolve_cycles),
        )
        dissolved_count = dissolved.rowcount

        # Demote priority on gaps past decay threshold (but below dissolve)
        demoted_high = self.db_conn.execute(
            "UPDATE questions SET priority = 'medium' "
            "WHERE status = 'open' AND priority = 'high' AND sleep_cycles_seen >= ?",
            (decay_cycles,),
        )
        demoted_med = self.db_conn.execute(
            "UPDATE questions SET priority = 'low' "
            "WHERE status = 'open' AND priority = 'medium' AND sleep_cycles_seen >= ?",
            (decay_cycles,),
        )
        demoted_count = demoted_high.rowcount + demoted_med.rowcount

        self.db_conn.commit()

        if dissolved_count or demoted_count:
            logger.info(
                f"Gap decay: {dissolved_count} dissolved (>={dissolve_cycles} cycles), "
                f"{demoted_count} demoted (>={decay_cycles} cycles)"
            )
        return dissolved_count, demoted_count

    def delete_question(self, question_id):
        """Delete a question."""
        self.db_conn.execute(
            "DELETE FROM questions WHERE id = ?", (question_id,)
        )
        self.db_conn.commit()

    def delete_all_questions(self):
        """Delete all questions."""
        self.db_conn.execute("DELETE FROM questions")
        self.db_conn.commit()

    def close(self):
        if self.db_conn:
            self.db_conn.close()

    @staticmethod
    def _row_to_dict(row):
        """Convert a sqlite3.Row to a dict with parsed JSON fields."""
        d = dict(row)
        if d.get("topic_tags"):
            try:
                d["topic_tags"] = json.loads(d["topic_tags"])
            except (json.JSONDecodeError, TypeError):
                d["topic_tags"] = []
        else:
            d["topic_tags"] = []
        return d
